random_split:
  ratio: 0.8
  random_seed: 0
  train_dataset:
    split: training
    cameras: null
    subjects: null
    actions: null
  val_dataset:
    split: validation
    cameras: null
    subjects: null
    actions: null

cross_camera_split:
  train_dataset:
    split: training
    cameras: [ kinect_000, kinect_002, kinect_003, kinect_004, kinect_005, kinect_006, kinect_008, iphone ]
    subjects: null
    actions: null
  val_dataset:
    split: validation
    cameras: [ kinect_001, kinect_007, kinect_009]
    subjects: null
    actions: null

cross_subject_split:
  train_dataset:
    split: training
    cameras: null
    subjects: [ 
      p001119, p001176, p000491, p000497, p001096, p001194, p000785, p001135, p000530, 
      p000977, p000554, p000480, p000722, p001183, p000556, p000881, p000478, p000997, 
      p000826, p000544, p001188, p000832, p000817, p000938, p000956, p000894, p000891, 
      p000443, p000972, p000568, p000521, p000495, p100069, p000913, p000510, p000901, 
      p000442, p000469, p000503, p000518, p000582, p000738, p000493, p000808, p001203, 
      p100064, p001199, p000851, p000539, p000978, p001134, p000731, p001163, p000931, 
      p000502, p100065, p000829, p001040, p000454, p001088, p000511, p000846, p001231, 
      p000857, p000548, p000526, p001115, p001042, p000536, p000833, p001225, p001114, 
      p000494, p000549, p000875, p000893, p000598, p001005, p000878, p001049, p000743, 
      p001221, p001121, p000487, p001172, p000490, p001125, p000802, p000450, p000794, 
      p000484, p000707, p000597, p000547, p000989, p000522, p000838, p001207, p000902, 
      p000540, p000757, p000584, p000476, p000513, p001226, p000908, p001156, p000545, 
      p000807, p000538, p001123, p000834, p000842, p000543, p000506, p000446, p000533, 
      p000566, p000852, p000593, p000449, p000813, p001195, p000998, p001190, p000447, 
      p000915, p001113, p000509, p001008, p000923, p000550, p000945, p000872, p000789, 
      p000874, p000498, p000859, p001182, p000592, p100090, p000507, p000830, p000448, 
      p001048, p001017, p000847, p000561, p001120, p000470, p001157, p001197, p000570, 
      p001024, p100084, p000837, p000569, p100086, p000571, p000703, p000948, p000471, 
      p000970, p000499, p000877, p000439, p000914, p001189, p001031, p001193, p000492, 
      p001018, p000466, p000440, p000535, p000701, p000758, p000455, p000810, p000771, 
      p000858, p000588, p000936, p000921, p000555, p001148, p001129, p001002, p000821, 
      p001202, p000926, p000520, p000741, p000702, p000805, p000793, p000475, p001187, 
      p100072, p000482, p000456, p000917, p000483, p000854, p000451, p000529, p000525, 
      p001004, p000474, p000843, p000961, p001126, p000880, p001109, p000481, p001144, 
      p000537, p000816, p000963, p000565, p000764, p001037, p000845, p000512, p000879, 
      p000853, p001039, p000955, p001091, p000952, p000969, p000839, p001178, p000966, 
      p000585, p000559, p001216, p100067, p000939, p000534, p000572, p000587, p001117, 
      p001161, p001036, p000452, p000783, p000792, p000558, p000486, p000595, p000552, 
      p100089, p000546, p000441, p000973, p000517, p001146, p000844, p001122, p001001, 
      p000496, p000528, p000541, p000828, p000924, p001196, p000465, p000488, p001124, 
      p000531, p000542
     ]
    actions: null
  val_dataset:
    split: validation
    cameras: null
    subjects: [
      p000532, p000514, p001204, p001147, p000742, p000444, p001052, p000823, p000575, 
      p000453, p000457, p000814, p000567, p000831, p000983, p001167, p000438, p000553, 
      p000907, p000519, p000985, p000835, p001162, p001192, p001191, p000827, p001159, 
      p000861, p000527, p000580, p000508, p000912, p001132, p000551, p000477, p000971, 
      p001139, p000984, p000756, p001168, p000557, p000959, p001201, p100085, p000706, 
      p001030, p001151, p000560, p001111, p000922, p000864, p000904, p100092, p000942, 
      p000964, p001142, p000988, p000996, p001028, p000700, p000590, p000504, p000524, 
      p000790, p000577, p001210, p000841, p001110
    ]

cross_action_split:
  train_dataset:
    split: training
    cameras: null
    subjects: null
    actions: [
      a000994, a001441, a000050, a000215, a000014, a005731, a006006, a000197, a000053, 
      a001231, a000040, a005710, a000206, a003006, a000219, a001241, a000017, a006002, 
      a000087, a001236, a000086, a001238, a000025, a003007, a000095, a001072, a000091, 
      a000190, a001306, a001422, a001424, a000092, a000063, a000220, a005823, a001247, 
      a001224, a000388, a000149, a000395, a000279, a005671, a000094, a005696, a003004, 
      a000082, a000078, a000218, a000056, a000157, a005354, a001312, a006003, a005751, 
      a005341, a000681, a000213, a000065, a000041, a000207, a000151, a000993, a000225, 
      a005126, a000198, a000622, a000083, a000024, a000176, a000203, a000134, a000081, 
      a005746, a000194, a001301, a000027, a000154, a000084, a005611, a000136, a001226, 
      a005770, a001199, a000019, a000212, a005516, a001234, a000029, a000107, a005700, 
      a005809, a000792, a000046, a000048, a005801, a001036, a000132, a001230, a000182, 
      a000126, a000096, a000175, a000228, a000214, a000155, a000031, a000897, a003005, 
      a005793, a000079, a000061, a000093, a005386, a006001, a000071, a005738, a000145, 
      a005828, a001252, a000064, a000205, a001281, a001423, a001285, a000076, a001083, 
      a006007, a001239, a000152, a005070, a000914, a000200, a000074, a000036, a001425, 
      a000085, a001251, a000160, a000011, a001023, a000073, a000146, a001362, a000170, 
      a000209, a000032, a000988, a005316, a005191, a001415, a005129, a000147, a000047, 
      a000043, a000184, a000968, a000326, a001026, a000208, a005135, a000140, a000802, 
      a005371, a099999, a000978, a000210, a001082, a000269, a000177, a005121, a005814, 
      a001147, a000790, a001413, a001134, a000035, a000793, a000051, a000141, a000226, 
      a001135, a000042, a000026, a005137, a000652, a005311, a001225, a000188, a000069, 
      a000148, a000285, a000062, a001300, a000221, a000108, a000156, a000158, a000001
    ]
  val_dataset:
    split: validation
    cameras: null
    subjects: null
    actions: [
      a000039, a005855, a003011, a000992, a005711, a000173, a000054, a005730, a001392, 
      a005240, a000306, a005571, a000153, a001307, a005591, a000162, a000379, a000223, 
      a001242, a005073, a000224, a000894, a000396, a000055, a000049, a001309, a000130, 
      a000986, a001131, a000178, a005401, a001398, a000211, a000701, a001426, a006000, 
      a000150, a000075, a001391, a001454, a001240, a000072, a001244, a001444, a003012, 
      a005008, a000030, a000070, a000080
    ]